
from django.utils.deprecation import MiddlewareMixin
from django.urls import resolve
from .signals import post_request_signal

class PostRequestMiddleware(MiddlewareMixin):
    def process_response(self, request, response):
        # Check if the response is generated by the specific view
        resolved_view = resolve(request.path_info)
        if resolved_view.func.__name__ == 'facial_recognition_verify':  # Change 'my_view' to your view function name
            # Trigger the signal only for the specific view
            post_request_signal.send(sender=self.__class__, request=request, response=response)
        return response
